# Generated by Django 4.1.2 on 2023-07-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
